version: '3'
services:
  mojolicious:
    container_name: mojolicious
    build:
      context: ./apps/mojolicious/
      dockerfile: Dockerfile
    volumes:
      - ./apps/mojolicious/:/app/
    ports:
      - ${MOJOLICIOUS_PORT}:${MOJOLICIOUS_PORT}